version: '3'

services:
  ghost:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://localhost:8080
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql
    restart: always
    volumes:
      - mydb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - my-network

volumes:
  mydb:

networks:
  my-network: