version: '3.1'

services:

  db:
    image: mysql
    restart: always
    container_name: sequelize_exercises_01
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

    volumes:
      - dbvolume:/var/lib/mysql
    
volumes:
  dbvolume:
