version: '3'

services: 
  db:
    image: mysql:5.7
    volumes:
      - my-datavolume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: trybedb
    ports:
      - 3306:3306

volumes:
  my-datavolume:
